Solucion_Sencillo_Project_DSW/Sencillo_Project_DSW/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sencillo_Project_DSW.Models
{
    public class Producto
    {
        public int idProducto { get; set; } 
        public string descripcion { get; set; }
        public string marca { get; set; }
        public decimal precio { get; set; }
        public int stock { get; set; }
        public string medida { get; set; }
        public string estado { get; set; }
        public int idCategoria { get; set; }
    }
}

Solucion_Sencillo_Project_DSW/Sencillo_Project_DSW/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using Sencillo_Project_DSW.Models;

namespace Sencillo_Project_DSW.Controllers
{
    public class ProductosController : Controller
    {
        string cadena = ConfigurationManager.ConnectionStrings["cn"].ConnectionString;

        

        IEnumerable<Producto> productos(string desc = "")
        {
            List<Producto> temporal = new List<Producto>();
            SqlConnection cn = new SqlConnection(cadena);
            SqlCommand cmd = new SqlCommand("sp_listar_prod", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@descrip", desc);

            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                Producto reg = new Producto();
                reg.idProducto = dr.GetInt32(0);
                reg.descripcion = dr.GetString(1);
                reg.marca = dr.GetString(2);
                reg.precio = dr.GetDecimal(3);
                reg.stock = dr.GetInt32(4);
                reg.medida = dr.GetString(5);
                reg.estado = dr.GetString(6);
                reg.idCategoria = dr.GetInt32(7);
                temporal.Add(reg);
            }
            dr.Close(); cn.Close();
            return temporal;
        }

        IEnumerable<Producto> filtro(string nombre = null)
        {
            if (nombre == null)
                return new List<Producto>();
            else
                return productos().Where(p => p.descripcion.StartsWith(nombre,
                    StringComparison.CurrentCultureIgnoreCase)).ToList();
        }

        public ActionResult Index(string nombre = "", int p = 0, string flecha = "")
        {
            //para el  login
            ViewBag.usuario = InicioSesion();

            if(Session["carrito"] == null)
            {
                Session["carrito"] = new List<Pedido>();
                ViewBag.carrito = "null";
            }

            ViewBag.carrito = "carrito";

            int f = 8;
            int c = productos(nombre).Count();
            int npags = c % f == 0 ? c / f : c / f + 1;

            ViewBag.p = p;
            ViewBag.npags = npags;

            if (flecha == ">>")
            {
                ViewBag.p = p + 1;
            }
            else if (flecha == "<<")
            {
                ViewBag.p = p - 1;
            }

            // SE ENVIA LA LISTA DE PRODUCTOS
            return View(productos(nombre).Skip(p * f).Take(f));
        }

        Producto Buscar(int? id = null)
        {
            if (id == null)
                return new Producto();
            else
                return productos().Where(p => p.idProducto == id).FirstOrDefault();

        }

        public ActionResult detailsProducto(int? id = null)
        {
            if (id == null) return RedirectToAction("Index");

            if (Session["carrito"] == null)
            {
                Session["carrito"] = new List<Pedido>();
                ViewBag.carrito = "null";
            }

            ViewBag.carrito = "carrito";

            //para el  login
            ViewBag.usuario = InicioSesion();
            return View(Buscar(id));
        }

        /*public ActionResult Index()
        {
            //para el  login
            ViewBag.usuario = InicioSesion();
            return View(productos());
        }*/

        /*OPERACIONES PARA EL  FUNCIONAMIENTO DEL  LOGIN*/

        Tipo_Usuario Buscar(string email, string clave)
        {
            //buscar al cliente ejecutando sp_logueo

            Tipo_Usuario reg = null;

            using (SqlConnection cn = new SqlConnection(cadena))
            {
                SqlCommand cmd = new SqlCommand("sp_logueo", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@email", email);
                cmd.Parameters.AddWithValue("@contraseña", clave);
                cn.Open();

                SqlDataReader dr = cmd.ExecuteReader();
                if (dr.Read())
                {


                    reg = new Tipo_Usuario()
                    {
                        //id_tipo = dr["id_tipo"].ToString(),

                        descripcion = dr["descripcion"].ToString()
                    };

                }
                dr.Close(); cn.Close();
            }
            return reg;
        }

        public ActionResult Inicio() // creamos  vista  ,  plantilla :empty(sin modelo)
        {
            return View();

        }

        [HttpPost]
        public ActionResult Inicio(string email, string clave)
        {

            Tipo_Usuario reg = Buscar(email, clave);
            if (reg == null)
            {
                ViewBag.mensaje = "Usuario o clave Incorrecta";
                return View();
            }
            else
            {
                Session["login2"] = reg;
                return RedirectToAction("Index");
            }
        }

        public ActionResult Cerrar()
        {
            Session["login2"] = null;
            return RedirectToAction("Index");
        }

        string InicioSesion()
        {
            if (Session["login2"] == null)
            {
                return null;
            }
            else 
            {
                return (Session["login2"] as Tipo_Usuario).descripcion;
            }
        }

        /*******************************************************/
        
        [HttpPost]public ActionResult DetailsProducto(int id, int cantidad, int stock)
        {
            ViewBag.usuario = InicioSesion();

            if (Session["carrito"] == null)
            {
                Session["carrito"] = new List<Pedido>();
                ViewBag.carrito = "null";
            }

            ViewBag.carrito = "carrito";

            if (cantidad > stock)
            {
                ViewBag.mensaje = "Ingrese una cantidad menor al stock";
                return View(Buscar(id));
            }

            //Session["carrito"] = new List<Pedido>();

            Producto reg = Buscar(id);

            Pedido it = new Pedido()
            {
                id_producto = reg.idProducto,
                descripcion = reg.descripcion,
                medida = reg.medida,
                precio = reg.precio,
                cantidad = cantidad,
            };
            List<Pedido> temporal = (List<Pedido>)Session["carrito"];
            temporal.Add(it);

            ViewBag.mensaje = "Producto agregado";
            return View(reg);
        }

        public ActionResult carrito()
        {
            ViewBag.usuario = InicioSesion();
            // Session["boleta"] = new List<Pedido>();

            return View((List<Pedido>)Session["carrito"]);
        }

        public ActionResult Delete(int id)
        {
            List<Pedido> temporal = (List<Pedido>)Session["carrito"];

            Pedido reg = temporal.Find(i => i.id_producto == id);
            temporal.Remove(reg);

            return RedirectToAction("carrito");
        }

        [HttpPost]public ActionResult carrito(string mns)
        {
            if (Session["login2"] == null)
            {
                ViewBag.mensaje = "Debe iniciar sesion para realizar una compra";
                return View((List<Pedido>)Session["carrito"]);
            }

            Session["boleta"] = null;

            Session["boleta"] = new List<Pedido>();

            Session["boleta"] = (List<Pedido>)Session["carrito"];

            // Session["login2"] = null;
            Session["carrito"] = null;

            return RedirectToAction("boleta");
        }

        public ActionResult boleta()
        {
            // Session["boleta"] = new List<Pedido>();
            Session["carrito"] = new List<Pedido>();

            ViewBag.usuario = InicioSesion();

            ViewBag.fecha = DateTime.Now.ToString("dd-MM-yyyy");
            ViewBag.hora = DateTime.Now.ToString("hh:mm:ss");

            return View((List<Pedido>)Session["boleta"]);
        }
    }
}

Solucion_Sencillo_Project_DSW/Sencillo_Project_DSW/Views/Productos/Index.cshtml
@model IEnumerable<Sencillo_Project_DSW.Models.Producto>
@{
    ViewBag.Title = "Index";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
<title>SENCILLO | Cada vez más cerca</title>

<style>
    .slider {
        margin-top: 140px;
    }
</style>

<!-- CARRUSEL DE FOTOS-->
<div class="slider">
    <ul>
        <img src="~/img/index-img/banner-1.jpg" alt="">
        <img src="~/img/index-img/banner-2.jpg" alt="">
    </ul>
</div>
<br />
<div class="row row-cols-1 row-cols-md-4 g-4">
    @foreach (var item in Model)
    {
    <div class="col">
        <div class="card h-100">
            <img src="@Url.Content(string.Format("~/img/productos/{0}.jpg", item.idProducto))" class="card-img-top" />
            <div class="card-body">
                @Html.DisplayFor(modelItem => item.marca, new { @class = "card-title" })
                <p class="card-text">
                    @Html.DisplayFor(modelItem => item.descripcion) x @Html.DisplayFor(modelItem => item.medida)<br />
                    S/ @Html.DisplayFor(modelItem => item.precio)
                </p>
            </div>
            <div class="card-footer">
                <small class="text-muted">
                    @Html.ActionLink("Detalle", "detailsProducto", new { id = item.idProducto, @class = "btn btn-primary" })
                </small>
            </div>
        </div>
    </div>
    }
</div>
<div class="text-center m-5">
    @Html.ActionLink("|<", "Index", new { p = 0 }, new { @class = "btn btn-primary" })

    @Html.ActionLink("<<", "Index", new { p = (int)ViewBag.p - 1 }, new { @class = "btn btn-primary" })

    @Html.Label(" " + (int)ViewBag.p + " ")

    @Html.ActionLink(">>", "Index", new { p = (int)ViewBag.p + 1 }, new { @class = "btn btn-primary" })

    @Html.ActionLink(">|", "Index", new { p = (int)ViewBag.npags - 1 }, new { @class = "btn btn-primary" })
</div>

Solucion_Sencillo_Project_DSW/Sencillo_Project_DSW/Views/Productos/Inicio.cshtml
@{
    ViewBag.Title = "Inicio";
}


@{
    Layout = null;
}

    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="~/css/login.css">
    </head>
    <body>
        <section>
            <div class="form-container">

                <h1>Iniciar Sesion</h1>
                <div class="mensaje-2">

                    @ViewBag.mensaje

                </div>
                <form action="Inicio" method="POST">

                    <div class="control">

                        <label for="name">Correo</label>

                        <input type="text" id="name" name="email">

                    </div>

                    <div class="control">

                        <label for="psw">Contraseña</label>
                        <input type="password" id="psw" name="clave">

                    </div>

                    <span><input type="checkbox"> Recordame</span>
                    <div class="control">
                        <input type="submit" class="btn" value="Inciar">
                    </div>
                </form>
                <p><a href="~/Registro/Registro">Registrarse</a></p>


            </div>
        </section>
    </body>
    </html>

Solucion_Sencillo_Project_DSW/Sencillo_Project_DSW/Views/Productos/boleta.cshtml
@model IEnumerable<Sencillo_Project_DSW.Models.Pedido>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>boleta</title>
    <style>
        body {
            margin-top: 200px;
        }
    </style>
</head>
<body>
    <div class="container">
        <span class="m-2">Fecha: @ViewBag.fecha</span><br />
        <span class="m-2">Hora: @ViewBag.hora</span>
        <table class="table table-striped">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.cantidad)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.precio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.monto)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cantidad)
                    </td>
                    <td>
                        S/.@Html.DisplayFor(modelItem => item.precio)
                    </td>
                    <td>
                        S/.@Html.DisplayFor(modelItem => item.monto)
                    </td>
                </tr>
            }
            <tr>
                <td></td>
                <td></td>
                <td>Total</td>
                <td>S/.@Model.Sum(m => m.monto)</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>@Html.ActionLink("Salir", "Index", null, new { @class="btn btn-danger"})</td>
            </tr>
        </table>
    </div>
</body>
</html>

Solucion_Sencillo_Project_DSW/Sencillo_Project_DSW/Views/Productos/carrito.cshtml
@model IEnumerable<Sencillo_Project_DSW.Models.Pedido>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/estilos-carrito.css" rel="stylesheet">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>SENCILLO | Cada vez más cerca</title>
    <style>
        body {
            margin-top: 140px;
        }
    </style>
</head>
<body>
    <div class="body__compra">
        <div class="lista__productos">
            <div class="alert-danger text-center p-3">@ViewBag.mensaje</div>
            <h1>Mi Carrito</h1>
            <hr />
            <br />
            @foreach (var item in Model)
            {
                <div class="item_lista">
                    <div class="image_item">
                        <img src="@Url.Content(string.Format("~/img/productos/{0}.jpg", item.id_producto))">
                    </div>
                    <div class="content_item">
                        <div class="descripcion_prod">
                            <div class="title_descripcion">
                                <h1>@Html.DisplayFor(modelItem => item.descripcion)</h1>
                                <span>@Html.DisplayFor(modelItem => item.medida)</span>
                            </div>
                            <div class="content_descripcion">
                                <span>Precio: <b>S/. @Html.DisplayFor(modelItem => item.precio)</b></span>
                                <span>Cantidad: <b>@Html.DisplayFor(modelItem => item.cantidad)</b></span>
                                <span>Total: <b>S/. @Html.DisplayFor(modelItem => item.monto)</b></span>
                            </div>
                        </div>
                        <div class="accion_item">
                            <!--<button type="button" class="btn_editar">Quitar</button>-->
                            @Html.ActionLink("Quitar", "Delete", new { id = item.id_producto }, new { @class="btn_delete"})
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="resumen__compra">
            <h2>RESUMEN DE COMPRA</h2>
            <hr>
            <div class="descripcion_compra">
                <div class="text_compra">
                    <span>Subtotal: </span><b>S/.@Model.Sum(m => m.monto)</b>
                </div>
                <div class="text_compra">
                    <span>TOTAL: </span><b style="color: #e42958">S/.@Model.Sum(m => m.monto)</b>
                </div>
            </div>
            <hr>
            @using (Html.BeginForm("carrito", "Productos", FormMethod.Post))
            {
                <div class="accion_compra">
                    @Html.Hidden("mns", "mensaje")
                    <button type="submit" class="btn_pagar">Finalizar Compra</button>
                    <!--<button type="button" class="btn_continuar">Continuar Comprando</button>-->
                    @Html.ActionLink("Seguir comprando", "Index", null, new { @class = "btn_continuar" })
                </div>
            }
        </div>
    </div>
</body>
</html>

Solucion_Sencillo_Project_DSW/Sencillo_Project_DSW/Views/Productos/detailsProducto.cshtml
@model Sencillo_Project_DSW.Models.Producto

@{
    ViewBag.Title = "detailsProducto";
}
<!-- Carousel -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Glide.js/3.4.1/css/glide.core.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Glide.js/3.4.1/css/glide.theme.min.css">
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<!-- Animate On Scroll -->
<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
<!-- Custom StyleSheet -->
<link rel="stylesheet" href="~/css/product.css" />
<title>SENCILLO | Cada vez más cerca</title>

<style>
    #main {
        margin-top: 140px;
    }
</style>

<main id="main">
    <div class="container">
        <div class="alert-danger text-center p-3">@ViewBag.mensaje</div>
        <!-- Products Details -->
        <section class="section product-details__section">
            @using (Html.BeginForm("DetailsProducto", "Productos", FormMethod.Post))
            {
                <div class="product-detail__container">
                    <div class="product-detail__left">
                        <div class="details__container--left">
                            <div class="product__picture" id="product__picture">
                                <div class="picture__container">
                                    <img src="@Url.Content(string.Format("~/img/productos/{0}.jpg", @Html.DisplayFor(model => model.idProducto)))" />
                                </div>
                            </div>
                            <div class="zoom" id="zoom"></div>
                        </div>
                        <div class="product-details__btn">

                            <button type="submit" class="add">Agregar al carrito</button>

                            @Html.ActionLink("Volver", "Index", null ,new { @class ="add"})

                        </div>
                    </div>

                    <div>
                        <div class="product-detail__right">
                            <div class="product-detail__content">
                                <h2>@Html.DisplayFor(model => model.marca)</h2>
                                <h1>@Html.DisplayFor(model => model.descripcion) x @Html.DisplayFor(model => model.medida)</h1>
                                <ul class="product__info">
                                    <li>
                                        <a class="in-stock">En stock (@Html.DisplayFor(model => model.stock) Items)</a>
                                        @Html.Hidden("stock", Model.stock)
                                    </li>
                                </ul>
                                <div class="price">
                                    <span class="new__price">S/. @Html.DisplayFor(model => model.precio)</span>
                                </div>

                                <div class="product__info-container">
                                    <ul class="product__info">
                                        <li>
                                            <div class="input-counter">
                                                <span>Cantidad: </span>
                                                <div>
                                                    @Html.TextBox("cantidad", 1, new { @class = "counter-btn" })
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </section>
    </div>
</main>